# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build-test:
    name: Build and run unit test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Run unit test with Jest
        run: npm run test:unit

      - name: Build application (which will located in /dist directory)
        run: npm run build

      - name: Upload build application artifact (located in /dist directory)
        uses: actions/upload-artifact@v2
        with:
          name: build-application
          path: dist

  cypress-run:
    name: E2E Cypress test
    runs-on: ubuntu-latest

    needs: build-test

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2

      - name: Download build application artifact (located in /dist directory)
        uses: actions/download-artifact@v2
        with:
          name: build-application
          path: dist

      - name: Display structure of downloaded files
        run: |
          cd dist
          ls -R

      - name: Display structure of working directory
        run: ls -la

      - name: Install last Cypress version
        run: npm install cypress --save-dev

      - name: Run Cypress and record
        uses: cypress-io/github-action@v2
        with:
          install: false
          record: true
          parallel: true
          browser: chrome
          tag: chrome
          start: npm start
          wait-on: "http://localhost:8080/"
          group: Tests on Google Chrome with Node.js v${{ matrix.node-version }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - name: Upload Cypress screenshots (if E2E Cypress test failed)
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/e2e/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: tests/e2e/videos/
